<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="_csrf" content="${_csrf.token}"/>
    <meta name="_csrf_header" content="${_csrf.headerName}"/>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous">

    <title>Online Wallet</title>

    <link rel="icon" href="/static/favicon/favicon.svg">
    <link rel="apple-touch-icon" href="/static/favicon/favicon-apple.png">
    <link rel="manifest" href="/static/favicon/manifest.json">
    <link rel="shortcut icon" href="/static/favicon/favicon-32.png" sizes="any">

    <meta name="theme-color" content="#ffffff">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <h1 class="text-center mb-3 col-12">Something went wrong((9(</h1>
        <div class="col-12 mb-3 text-center">
            <a href="/" class="btn btn-lg btn-primary mx-auto">Home page</a>
        </div>
        <br>
        <img src="/static/img/spiderman.gif" class="mx-auto col-4 img-fluid"
             alt="error" loading="lazy">
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>
</body>
</html>