insert into online_wallet.public.transactions_categories (is_income, category)
values ('t', 'Other Income'),
       ('f', 'Other Expense'),
       ('t', 'Work'),
       ('t', 'Scholarship'),
       ('t', 'Gifts'),
       ('f', 'Subscriptions'),
       ('f', 'Education'),
       ('f', 'Clothes'),
       ('f', 'Entertainments'),
       ('f', 'Transport'),
       ('f', 'Food'),
       ('f', 'Rent'),
       ('f', 'Travelling'),
       ('t', 'Pension'),
       ('f', 'To lend'),
       ('t', 'To borrow'),
       ('f', 'Taxes');
